[package]
name = "orange"
version = "0.1.0"
authors = ["Alex Kucherenko <kucherenko.email@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.state]
path = 'lib/state/'

[dependencies.render]
path = 'lib/render/'
