[package]
name = "orange"
version = "0.1.0"
authors = ["Alex Kucherenko <kucherenko.email@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.23"
thiserror = "1.0.11"

[build-dependencies]
fs_extra = "1.1.0"

[dependencies.state]
path = 'lib/state/'

[dependencies.render]
path = 'lib/render/'

[dependencies.gl]
path = 'lib/gl/'

[dependencies.assets]
path = 'lib/assets/'
